name: Python unittest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: run unittests
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd client && pip install -r requirements.txt
    - name: Run tests
      run: |
        cd client && python -m unittest discover -s tests -p "test_*.py"
        echo "All tests passed!"
    - name: Lint code
      run: |
        pip install flake8
        cd client && flake8 .
        echo "Linting passed!"
